# Generated by Django 5.0.4 on 2024-04-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('category', models.CharField(max_length=20)),
                ('link', models.URLField(blank=True)),
                ('date', models.CharField(max_length=80, verbose_name='date published project')),
            ],
        ),
    ]
