# Generated by Django 5.0.4 on 2024-04-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
