# Generated by Django 5.0.4 on 2024-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_remove_portfolioitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/', verbose_name='image')),
                ('body', models.TextField(blank=True, null=True, verbose_name='text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
    ]
